# Generated by Django 6.0.5 on 2026-06-03 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_observacoes'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orcamento'), ('ABERTO', 'Aberto'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Pedido de venda',
                'verbose_name_plural': 'Pedidos de venda',
                'ordering': ['-cadastrado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_venda', to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedidovenda')),
            ],
            options={
                'verbose_name': 'Item do pedido de venda',
                'verbose_name_plural': 'Itens do pedido de venda',
            },
        ),
    ]
